
["Spatial Harvesters - Common Config: "]

	["Spatial Harvesters - Common Config: "."Custom Harvester Outputs: "]
		#Custom outputs for the Ore Harvester.
		custom_ores = [["appliedenergistics2", "quartz_ore"], ["appliedenergistics2", "charged_quartz_ore"], ["routerreborn", "copper_ore"], ["rftoolsbase", "dimensionalshard_overworld"], ["rftoolsbase", "dimensionalshard_nether"], ["rftoolsbase", "dimensionalshard_end"], ["rhodonite", "block_ore_fluorite"], ["rhodonite", "block_ore_rhodonite"], ["exp_ore", "block_exp_ore"], ["rockcandy", "candy_ore"], ["lightestlamp", "boron_ore"], ["funores", "zombie_ore"], ["funores", "blaze_ore"], ["funores", "ghast_ore"], ["funores", "magma_cube_ore"], ["funores", "wither_skeleton_ore"], ["funores", "zombie_pigman_ore"], ["funores", "salmon_ore"], ["funores", "squid_ore"], ["funores", "cod_ore"], ["funores", "sheep_ore"], ["funores", "rabbit_ore"], ["funores", "pig_ore"], ["funores", "cow_ore"], ["funores", "chicken_ore"], ["funores", "bat_ore"], ["funores", "witch_ore"], ["funores", "spider_ore"], ["funores", "slime_ore"], ["funores", "phantom_ore"], ["funores", "skeleton_ore"], ["funores", "enderman_ore"], ["funores", "guardian_ore"], ["funores", "pufferfish_ore"], ["funores", "creeper_ore"], ["gobber2", "gobber2_ore"], ["gobber2", "gobber2_ore_nether"], ["gobber2", "gobber2_ore_end"], ["minecraft", "glowstone"], ["upgrade_aquatic", "embedded_ammonite"]]
		#Custom outputs for the Bio Harvester.
		custom_bios = []
		#Custom outputs for the Stone Harvester.
		custom_stones = []
		#Custom outputs for the Soil Harvester.
		custom_soils = [["minecraft", "clay"]]
		#Custom loot tables for the Loot Harvester.
		custom_loot_tables = [["minecraft", "chests/simple_dungeon"], ["minecraft", "chests/buried_treasure"], ["minecraft", "chests/desert_pyramid"], ["minecraft", "chests/abandoned_mineshaft"], ["minecraft", "chests/end_city_treasure"], ["minecraft", "chests/igloo_chest"], ["minecraft", "chests/jungle_temple"], ["minecraft", "chests/nether_bridge"], ["minecraft", "chests/pillager_outpost"], ["minecraft", "chests/shipwreck_map"], ["minecraft", "chests/shipwreck_treasure"], ["minecraft", "chests/stronghold_corridor"], ["minecraft", "chests/stronghold_corridor"], ["minecraft", "chests/stronghold_corridor"], ["minecraft", "chests/stronghold_crossing"], ["minecraft", "chests/stronghold_library"], ["minecraft", "chests/underwater_ruin_big"], ["minecraft", "chests/underwater_ruin_small"], ["minecraft", "chests/woodland_mansion"]]
		#Custom drops for the Mob Harvester.
		custom_mob_drops = [[["minecraft", "ender_dragon"], ["minecraft", "elytra"]], [["minecraft", "ender_dragon"], ["minecraft", "dragon_head"]], [["minecraft", "ender_dragon"], ["minecraft", "dragon_egg"]], [["minecraft", "ender_dragon"], ["minecraft", "dragon_breath"]]]

	["Spatial Harvesters - Common Config: "."Custom Harvester Tags: "]
		#Custom tags for the Ore Harvester.
		custom_ore_tags = [["forge", "ores"]]
		#Custom tags for the Bio Harvester.
		custom_bio_tags = [["forge", "crops"], ["forge", "leather"], ["forge", "feathers"], ["forge", "seeds"], ["forge", "dyes"], ["forge", "bones"], ["forge", "rods_wooden"], ["minecraft", "small_flowers"], ["minecraft", "logs"], ["minecraft", "planks"], ["minecraft", "saplings"], ["minecraft", "leaves"]]
		#Custom tags for the Stone Harvester.
		custom_stone_tags = [["forge", "cobblestone"], ["forge", "sandstone"], ["forge", "end_stones"], ["forge", "netherrack"]]
		#Custom tags for the Soil Harvester.
		custom_soil_tags = [["forge", "dirt"], ["forge", "sand"], ["forge", "soul_sand"], ["forge", "gravel"]]

	["Spatial Harvesters - Common Config: "."Minimum Harvester Tier Items - Format: [[modid, name, tier (1-8, must be string)], [modid, name, tier (1-8, must be string)]]: "]
		#Minimum Tier Ore Harvesters for given Ores.
		min_tier_ores = []
		#Minimum Tier Bio Harvesters for given Bios.
		min_tier_bios = []
		#Minimum Tier Stone Harvesters for given Stones.
		min_tier_stones = []
		#Minimum Tier Soil Harvesters for given Soils.
		min_tier_soils = []

	["Spatial Harvesters - Common Config: "."Harvester Blacklists: "]
		#Blacklist for the Ore Harvesters
		blacklist_ores = []
		#Blacklist for the Bio Harvesters
		blacklist_bios = []
		#Blacklist for the Stone Harvesters
		blacklist_stones = []
		#Blacklist for the Soil Harvesters
		blacklist_soils = []
		#Blacklist for the Loot Harvesters
		blacklist_loot = []
		#Blacklist for the Mob Harvesters
		blacklist_mobs = []

	["Spatial Harvesters - Common Config: "."Harvester Blacklists (By mod): "]
		#Blacklist for the Ore Harvesters (By mod)
		blacklist_ores_mod = []
		#Blacklist for the Bio Harvesters (By mod)
		blacklist_bios_mod = []
		#Blacklist for the Stone Harvesters (By mod)
		blacklist_stones_mod = []
		#Blacklist for the Soil Harvesters (By mod)
		blacklist_soils_mod = []
		#Blacklist for the Loot Harvesters (By mod)
		blacklist_loot_mod = []
		#Blacklist for the Mob Harvesters (By mod)
		blacklist_mobs_mod = []

	["Spatial Harvesters - Common Config: "."Harvester Blacklists (By tag): "]
		#Blacklist for the Ore Harvesters (By tag)
		blacklist_ores_tag = []
		#Blacklist for the Bio Harvesters (By tag)
		blacklist_bios_tag = [["botania", "special_flowers"]]
		#Blacklist for the Stone Harvesters (By tag)
		blacklist_stones_tag = []
		#Blacklist for the Soil Harvesters (By tag)
		blacklist_soils_tag = []

	["Spatial Harvesters - Common Config: "."Machine Speeds: "]
		#Speed for the Loot Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
		#Range: > 0
		loot_speed = 50

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Energy Generator Speeds: "]
			#Speed for the Heat Generator (in FE per tick)
			#Range: > 0
			speed_heat_generator = 10

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Ore Harvester Speeds: "]
			#Speed for the tier 1 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_1 = 400
			#Speed for the tier 2 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_2 = 350
			#Speed for the tier 3 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_3 = 300
			#Speed for the tier 4 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_4 = 250
			#Speed for the tier 5 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_5 = 200
			#Speed for the tier 6 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_6 = 150
			#Speed for the tier 7 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_7 = 100
			#Speed for the tier 8 Ore Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_ore_8 = 5

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Bio Harvester Speeds: "]
			#Speed for the tier 1 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_1 = 400
			#Speed for the tier 2 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_2 = 350
			#Speed for the tier 3 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_3 = 300
			#Speed for the tier 4 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_4 = 250
			#Speed for the tier 5 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_5 = 200
			#Speed for the tier 6 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_6 = 150
			#Speed for the tier 7 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_7 = 100
			#Speed for the tier 8 Bio Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_bio_8 = 5

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Stone Harvester Speeds: "]
			#Speed for the tier 1 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_1 = 400
			#Speed for the tier 2 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_2 = 350
			#Speed for the tier 3 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_3 = 300
			#Speed for the tier 4 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_4 = 250
			#Speed for the tier 5 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_5 = 200
			#Speed for the tier 6 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_6 = 150
			#Speed for the tier 7 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_7 = 100
			#Speed for the tier 8 Stone Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_stone_8 = 5

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Soil Harvester Speeds: "]
			#Speed for the tier 1 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_1 = 400
			#Speed for the tier 2 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_2 = 350
			#Speed for the tier 3 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_3 = 300
			#Speed for the tier 4 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_4 = 250
			#Speed for the tier 5 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_5 = 200
			#Speed for the tier 6 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_6 = 150
			#Speed for the tier 7 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_7 = 100
			#Speed for the tier 8 Soil Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			speed_soil_8 = 5

		["Spatial Harvesters - Common Config: "."Machine Speeds: "."Mob Harvester Speeds: "]
			#Speed for the Dark Mob Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			dark_mob_speed = 50
			#Speed for the Specific Mob Harvester (in ticks, there are 20 in a second. The lower this value, the faster.)
			#Range: > 0
			specific_mob_speed = 50

	["Spatial Harvesters - Common Config: "."Machine Prices: "]
		#Amount to multiply the price of the harvesters by to set their energy capacity.
		#Range: > 0
		harvester_capacity_multiplier = 100
		#Amount to multiply the price of the Dimensional Applicator by to set its energy capacity.
		#Range: > 0
		dimensional_applicator_capacity_multiplier = 100
		#Amount to multiply the price of the Heat Generator by to set its energy capacity.
		#Range: > 0
		heat_generator_capacity_multiplier = 100
		#Price for the Dimensional Applicator (in FE per operation)
		#Range: > 0
		price_dimensional_applicator = 1000
		#Price for the Loot Harvester (in FE per operation)
		#Range: > 0
		loot_price = 8000

		["Spatial Harvesters - Common Config: "."Machine Prices: "."Ore Harvester Prices: "]
			#Price for the tier 1 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_1 = 400
			#Price for the tier 2 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_2 = 600
			#Price for the tier 3 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_3 = 1000
			#Price for the tier 4 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_4 = 1500
			#Price for the tier 5 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_5 = 4000
			#Price for the tier 6 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_6 = 7000
			#Price for the tier 7 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_7 = 7500
			#Price for the tier 8 Ore Harvester (in FE per operation)
			#Range: > 0
			price_ore_8 = 8000

		["Spatial Harvesters - Common Config: "."Machine Prices: "."Bio Harvester Prices: "]
			#Price for the tier 1 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_1 = 400
			#Price for the tier 2 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_2 = 600
			#Price for the tier 3 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_3 = 1000
			#Price for the tier 4 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_4 = 1500
			#Price for the tier 5 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_5 = 4000
			#Price for the tier 6 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_6 = 7000
			#Price for the tier 7 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_7 = 7500
			#Price for the tier 8 Bio Harvester (in FE per operation)
			#Range: > 0
			price_bio_8 = 8000

		["Spatial Harvesters - Common Config: "."Machine Prices: "."Stone Harvester Prices: "]
			#Price for the tier 1 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_1 = 400
			#Price for the tier 2 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_2 = 600
			#Price for the tier 3 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_3 = 1000
			#Price for the tier 4 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_4 = 1500
			#Price for the tier 5 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_5 = 4000
			#Price for the tier 6 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_6 = 7000
			#Price for the tier 7 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_7 = 7500
			#Price for the tier 8 Stone Harvester (in FE per operation)
			#Range: > 0
			price_stone_8 = 8000

		["Spatial Harvesters - Common Config: "."Machine Prices: "."Soil Harvester Prices: "]
			#Price for the tier 1 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_1 = 400
			#Price for the tier 2 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_2 = 600
			#Price for the tier 3 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_3 = 1000
			#Price for the tier 4 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_4 = 1500
			#Price for the tier 5 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_5 = 4000
			#Price for the tier 6 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_6 = 7000
			#Price for the tier 7 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_7 = 7500
			#Price for the tier 8 Soil Harvester (in FE per operation)
			#Range: > 0
			price_soil_8 = 8000

		["Spatial Harvesters - Common Config: "."Machine Prices: "."Mob Harvester Prices: "]
			#Price for the Dark Mob Harvester (in FE per operation)
			#Range: > 0
			dark_mob_price = 8000
			#Price for the Specific Mob Harvester (in FE per operation)
			#Range: > 0
			specific_mob_price = 8000

	["Spatial Harvesters - Common Config: "."Dimensional Applicator Stats: "]
		#Amplifier for the Dimensional Applicator (The final value will be this * the number of Space Rippers.)
		#Range: > 0
		amplifier_dimensional_applicator = 1
		#Duration for the Dimensional Applicator (in ticks, 20 = one second, 220 = 11 seconds (Night Vision flashes at 10 or less)).
		#Range: > 0
		dimensional_applicator_duration = 240
		#How much to divide the Dimensional Applicator's duration by to get it's reapplication frequency (10 makes it every second if the duration is 220, just over if 240).
		#This can be less than one to make it take longer than the effect lasts (not recommended, though).
		#Range: 0.0 ~ 1.7976931348623157E308
		dimensional_applicator_divisor = 20.0
		#Whether the game should think the effects came from a beacon.
		dimensional_applicator_is_beacon_effect = true
		#Whether to show the particles of the effects.
		dimensional_applicator_show_particles = false
		#Whether to show the icons of the effects.
		dimensional_applicator_show_icon = false

	["Spatial Harvesters - Common Config: "."Enable / Disable: "]
		#Should the Chunk Loader have functionality?
		enable_chunk_loader = false
		#Should the Dimensional Applicator have functionality?
		enable_dimensional_applicator = false
		#Should the Heat Generator have functionality?
		enable_heat_generator = true
		#Should the Ore Harvesters have functionality?
		enable_ore_harvesters = true
		#Should the Bio Harvesters have functionality?
		enable_bio_harvesters = true
		#Should the Stone Harvesters have functionality?
		enable_stone_harvesters = true
		#Should the Soil Harvesters have functionality?
		enable_soil_harvesters = true
		#Should the Loot Harvester have functionality?
		enable_loot_harvester = true
		#Should the Dark Mob Harvester have functionality?
		enable_dark_mob_harvester = true
		#Should the Specific Mob Harvester have functionality?
		enable_specific_mob_harvester = true

	["Spatial Harvesters - Common Config: "."Misc: "]
		#Valid heat sources for the Heat Generator.
		valid_heat_sources = [["minecraft", "magma_block"], ["minecraft", "lava"], ["minecraft", "fire"]]
		#Hardness for the blocks (Iron Block is 5.)
		#Range: 0.0 ~ 3.4028234663852886E38
		block_hardness = 5.0
		#Resistance for the blocks (Iron Block is 6.)
		#Range: 0.0 ~ 3.4028234663852886E38
		block_resistance = 6.0
		#Chance for a harvester to output a shard (the higher the value, the less likely the shard, 0 means no shards.)
		#Range: > 0
		harvester_shard_chance = 75
		#Chance for a Mob Harvester to output a Mob Shard (the higher the value, the less likely the shard, 0 means no shards.)
		#Range: > 0
		mob_harvester_mob_shard_chance = 25
		#Light level for the machines to emit when active (a regular torch is 14, 0 to disable).
		#Range: > 0
		machine_light_level = 7
		#Multiplier for the break speed of the keys when configuring in that way (they won't actually break blocks).
		#Range: > 0
		key_break_speed_multiplier = 10

